# Generated by Django 6.0.2 on 2026-02-22 00:43

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('request_type', models.CharField(choices=[('gold', 'Gold Purchase Inquiry'), ('silver', 'Silver Purchase Inquiry'), ('investment', 'Investment Partnership'), ('other', 'Other Request')], max_length=50)),
                ('message', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
