# Generated by Django 6.0.2 on 2026-02-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0003_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
