# Generated by Django 6.0.2 on 2026-03-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0007_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
