# Generated by Django 6.0.2 on 2026-03-11 15:27

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0009_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
    ]
