# Generated by Django 6.0.2 on 2026-03-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0011_csrcategory_csrproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='csr/categories/'),
            preserve_default=False,
        ),
    ]
