# Generated by Django 6.0.2 on 2026-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0014_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('wildlife', 'Wildlife'), ('game_drives', 'Game Drives'), ('nile_river', 'Nile River'), ('safari_lodges', 'Safari Lodges'), ('kampala', 'Kampala'), ('student_tours', 'Student Tours')], max_length=50)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
