# Generated by Django 6.0.2 on 2026-05-31 18:15

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0016_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='tour-packages/')),
                ('duration', models.CharField(help_text='e.g. 3 Days / 2 Nights', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', tinymce.models.HTMLField()),
                ('itinerary', tinymce.models.HTMLField(help_text='Day-by-day schedule')),
                ('included', tinymce.models.HTMLField(help_text="What's included")),
                ('excluded', tinymce.models.HTMLField(help_text="What's excluded")),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
